### ISSUE TITLE
Doesn't show 'public' scheme for PostgreSQL db

### ISSUE THREAD

**Issue by aburakovskiy** [TeamSQL/desktop-app#42]
OS: Mac OS X 10.12
Database Type: PostgreSQL
Connect through VPN. For local connections working well.
TeamSQL doesn't load or show _public_ scheme 

TeamSQL view
<img width="211" alt="2017-03-20_1921" src="https://cloud.githubusercontent.com/assets/1153385/24109718/936feaba-0da2-11e7-985d-97f7645e725a.png">

pgAdmin3 view
<img width="212" alt="2017-03-20_1924" src="https://cloud.githubusercontent.com/assets/1153385/24109826/e1a50f80-0da2-11e7-882a-81f60f5f2670.png">

**Comment by abacigil** [comment]
Fixed

**Comment by aburakovskiy** [comment]
Should it be fixed in version 0.9.91?

**Comment by abacigil** [comment]
@aburakovskiy Yes it should be.

Can you confirm that?

**Comment by aburakovskiy** [comment]
Unfortunately it is still reproduced
<img width="546" alt="2017-04-26_1709" src="https://cloud.githubusercontent.com/assets/1153385/25438886/72d268a0-2aa3-11e7-9d29-43fe9e3db1cd.png">
it happens only when connect **through VPN**

**Comment by rasputino** [comment]
OS: Windows_NT x64 10.0.14393
VERSION: 0.9.93
---------------
Database Type: Postgresql

I have the same problem, was not solved in version 0.9.91?

![image](https://cloud.githubusercontent.com/assets/2887216/25792463/018af306-33c7-11e7-9ad5-a2acbd042741.png)

**Comment by aburakovskiy** [comment]
Would you plan reopen this issue again and fix in the next release?

**Comment by MetaDonk** [comment]
I am using latest Windows build and experiencing this exact issue.  Can see public schema, but can't see any tables.
